In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

matches_path = "../data/matches_1930_2022.csv"

df = pd.read_csv(matches_path)

In [15]:
matches = df[["home_team", "away_team", "Year", "home_score", "away_score"]].copy()

matches = matches.rename(columns = {
    "away_team": "away_team",
    "home_team": "home_team",
    "Year": "year",
    "away_score": "away_score",
    "home_score": "home_score"
})

matches["goals"] = (
    matches["home_score"] + matches["away_score"]
)

matches

         home_team away_team  year  home_score  away_score  goals
0        Argentina    France  2022           3           3      6
1          Croatia   Morocco  2022           2           1      3
2           France   Morocco  2022           2           0      2
3        Argentina   Croatia  2022           3           0      3
4          Morocco  Portugal  2022           1           0      1
..             ...       ...   ...         ...         ...    ...
959      Argentina    France  1930           1           0      1
960     Yugoslavia    Brazil  1930           2           1      3
961        Romania      Peru  1930           3           1      4
962  United States   Belgium  1930           3           0      3
963         France    Mexico  1930           4           1      5

[964 rows x 6 columns]

In [16]:
total_match = (
    matches
    .groupby(["year"])
    .size()
    .reset_index(name="total_matches")
)

total_match

    year  total_matches
0   1930             18
1   1934             17
2   1938             18
3   1950             22
4   1954             26
5   1958             35
6   1962             32
7   1966             32
8   1970             32
9   1974             38
10  1978             38
11  1982             52
12  1986             52
13  1990             52
14  1994             52
15  1998             64
16  2002             64
17  2006             64
18  2010             64
19  2014             64
20  2018             64
21  2022             64

In [17]:
home_teams = matches[["year", "home_team", "home_score"]].copy()
home_teams = home_teams.rename(columns={
    "home_team": "team",
    "home_score": "goals"
})

away_teams = matches[["year", "away_team", "away_score"]].copy()
away_teams = away_teams.rename(columns={
    "away_team": "team",
    "away_score": "goals"
})

teams_by_year = pd.concat([home_teams, away_teams], ignore_index=True)

teams_by_year

      year       team  goals
0     2022  Argentina      3
1     2022    Croatia      2
2     2022     France      2
3     2022  Argentina      3
4     2022    Morocco      1
...    ...        ...    ...
1923  1930     France      0
1924  1930     Brazil      1
1925  1930       Peru      1
1926  1930    Belgium      0
1927  1930     Mexico      1

[1928 rows x 3 columns]

In [18]:
total_teams = (
    teams_by_year
    .groupby("year")["team"]
    .nunique()
    .reset_index(name="total_teams")
)

total_teams

    year  total_teams
0   1930           13
1   1934           16
2   1938           15
3   1950           13
4   1954           16
5   1958           16
6   1962           16
7   1966           16
8   1970           16
9   1974           16
10  1978           16
11  1982           24
12  1986           24
13  1990           24
14  1994           24
15  1998           32
16  2002           32
17  2006           32
18  2010           32
19  2014           32
20  2018           32
21  2022           32

In [19]:
year_summary = total_match.merge(
    total_teams,
    on="year",
    how="left"
)

year_summary

    year  total_matches  total_teams
0   1930             18           13
1   1934             17           16
2   1938             18           15
3   1950             22           13
4   1954             26           16
5   1958             35           16
6   1962             32           16
7   1966             32           16
8   1970             32           16
9   1974             38           16
10  1978             38           16
11  1982             52           24
12  1986             52           24
13  1990             52           24
14  1994             52           24
15  1998             64           32
16  2002             64           32
17  2006             64           32
18  2010             64           32
19  2014             64           32
20  2018             64           32
21  2022             64           32

In [20]:
total_goals = (
    teams_by_year
    .groupby("year")["goals"]
    .sum()
    .reset_index(name="total_goals")
)

total_goals

    year  total_goals
0   1930           70
1   1934           70
2   1938           84
3   1950           88
4   1954          140
5   1958          126
6   1962           89
7   1966           89
8   1970           95
9   1974           97
10  1978          102
11  1982          146
12  1986          132
13  1990          115
14  1994          141
15  1998          171
16  2002          161
17  2006          147
18  2010          145
19  2014          171
20  2018          169
21  2022          172

In [21]:
year_summary = year_summary.merge(
    total_goals,
    on="year",
    how="left"
)

year_summary

    year  total_matches  total_teams  total_goals
0   1930             18           13           70
1   1934             17           16           70
2   1938             18           15           84
3   1950             22           13           88
4   1954             26           16          140
5   1958             35           16          126
6   1962             32           16           89
7   1966             32           16           89
8   1970             32           16           95
9   1974             38           16           97
10  1978             38           16          102
11  1982             52           24          146
12  1986             52           24          132
13  1990             52           24          115
14  1994             52           24          141
15  1998             64           32          171
16  2002             64           32          161
17  2006             64           32          147
18  2010             64           32          145
19  2014             64           32          171
20  2018             64           32          169
21  2022             64           32          172

In [22]:
year_summary["avg_goals_per_match"] = (
    year_summary["total_goals"] / year_summary["total_matches"]
)

year_summary

    year  total_matches  total_teams  total_goals  avg_goals_per_match
0   1930             18           13           70             3.888889
1   1934             17           16           70             4.117647
2   1938             18           15           84             4.666667
3   1950             22           13           88             4.000000
4   1954             26           16          140             5.384615
5   1958             35           16          126             3.600000
6   1962             32           16           89             2.781250
7   1966             32           16           89             2.781250
8   1970             32           16           95             2.968750
9   1974             38           16           97             2.552632
10  1978             38           16          102             2.684211
11  1982             52           24          146             2.807692
12  1986             52           24          132             2.538462
13  1990             52           24          115             2.211538
14  1994             52           24          141             2.711538
15  1998             64           32          171             2.671875
16  2002             64           32          161             2.515625
17  2006             64           32          147             2.296875
18  2010             64           32          145             2.265625
19  2014             64           32          171             2.671875
20  2018             64           32          169             2.640625
21  2022             64           32          172             2.687500

In [23]:
max_goals_in_match = (
    matches.groupby("year")["goals"]
    .max()
    .reset_index(name="max_goals_in_match")
)

max_goals_in_match

    year  max_goals_in_match
0   1930                   9
1   1934                   8
2   1938                  11
3   1950                   8
4   1954                  12
5   1958                  10
6   1962                   8
7   1966                   8
8   1970                   7
9   1974                   9
10  1978                   6
11  1982                  11
12  1986                   7
13  1990                   6
14  1994                   7
15  1998                   7
16  2002                   8
17  2006                   6
18  2010                   7
19  2014                   8
20  2018                   7
21  2022                   8

In [24]:
year_summary = year_summary.merge(
    max_goals_in_match,
    on="year",
    how="left"
)

year_summary

,year,total_matches,total_teams,total_goals,avg_goals_per_match,max_goals_in_match
0,1930,18,13,70,3.888889,9
1,1934,17,16,70,4.117647,8
2,1938,18,15,84,4.666667,11
3,1950,22,13,88,4.000000,8
4,1954,26,16,140,5.384615,12
5,1958,35,16,126,3.600000,10
6,1962,32,16,89,2.781250,8
7,1966,32,16,89,2.781250,8
8,1970,32,16,95,2.968750,7
9,1974,38,16,97,2.552632,9
10,1978,38,16,102,2.684211,6
11,1982,52,24,146,2.807692,11
12,1986,52,24,132,2.538462,7
13,1990,52,24,115,2.211538,6
14,1994,52,24,141,2.711538,7
15,1998,64,32,171,2.671875,7
16,2002,64,32,161,2.515625,8
17,2006,64,32,147,2.296875,6
18,2010,64,32,145,2.265625,7
19,2014,64,32,171,2.671875,8
20,2018,64,32,169,2.640625,7
21,2022,64,32,172,2.687500,8

In [25]:
high_score = matches[matches["goals"] > 5 ]

high_scoring_matches = (
    high_score.groupby("year")["goals"]
    .count()
    .reset_index(name="high_scoring_matches")
)

high_scoring_matches

    year  high_scoring_matches
0   1930                     4
1   1934                     3
2   1938                     8
3   1950                     4
4   1954                    11
5   1958                     6
6   1962                     3
7   1966                     2
8   1970                     3
9   1974                     3
10  1978                     3
11  1982                     4
12  1986                     5
13  1990                     2
14  1994                     1
15  1998                     1
16  2002                     3
17  2006                     2
18  2010                     1
19  2014                     4
20  2018                     5
21  2022                     6

In [26]:
year_summary = year_summary.merge(
    high_scoring_matches,
    on="year",
    how="left"
)

year_summary

,year,total_matches,total_teams,total_goals,avg_goals_per_match,max_goals_in_match,high_scoring_matches
0,1930,18,13,70,3.888889,9,4
1,1934,17,16,70,4.117647,8,3
2,1938,18,15,84,4.666667,11,8
3,1950,22,13,88,4.000000,8,4
4,1954,26,16,140,5.384615,12,11
5,1958,35,16,126,3.600000,10,6
6,1962,32,16,89,2.781250,8,3
7,1966,32,16,89,2.781250,8,2
8,1970,32,16,95,2.968750,7,3
9,1974,38,16,97,2.552632,9,3
10,1978,38,16,102,2.684211,6,3
11,1982,52,24,146,2.807692,11,4
12,1986,52,24,132,2.538462,7,5
13,1990,52,24,115,2.211538,6,2
14,1994,52,24,141,2.711538,7,1
15,1998,64,32,171,2.671875,7,1
16,2002,64,32,161,2.515625,8,3
17,2006,64,32,147,2.296875,6,2
18,2010,64,32,145,2.265625,7,1
19,2014,64,32,171,2.671875,8,4
20,2018,64,32,169,2.640625,7,5
21,2022,64,32,172,2.687500,8,6

In [27]:
year_summary.isna().sum()

year                    0
total_matches           0
total_teams             0
total_goals             0
avg_goals_per_match     0
max_goals_in_match      0
high_scoring_matches    0
dtype: int64